# Generated by Django 5.2.15 on 2026-06-04 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_ai_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='food',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='經度'),
        ),
    ]
